//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standartstyle.App_Code.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOODS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOODS()
        {
            this.GOOD_COLOR = new HashSet<GOOD_COLOR>();
            this.REPLY = new HashSet<REPLY>();
        }
    
        public int GOODCODE { get; set; }
        public Nullable<int> CATEGORYCODE { get; set; }
        public Nullable<int> IMAGECODE { get; set; }
        public Nullable<int> USERCODE { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOOD_COLOR> GOOD_COLOR { get; set; }
        public virtual GOODS_CATEGORY GOODS_CATEGORY { get; set; }
        public virtual IMAGE IMAGE { get; set; }
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPLY> REPLY { get; set; }
    }
}
