//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standartstyle.App_Code.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMAGE()
        {
            this.CBD_COLOR = new HashSet<CBD_COLOR>();
            this.GOODS = new HashSet<GOODS>();
        }
    
        public int IMAGECOED { get; set; }
        public Nullable<int> USERCODE { get; set; }
        public string NAME { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> UPLOAD_DATE { get; set; }
        public Nullable<bool> IS_MAIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CBD_COLOR> CBD_COLOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODS> GOODS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
