//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standartstyle.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int GoodsCode { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public Nullable<int> ImageCode { get; set; }
        public string GoodsName { get; set; }
        public string GoodsDescription { get; set; }
    
        public virtual GoodsCategory GoodsCategory { get; set; }
        public virtual Image Image { get; set; }
    }
}
