//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standartstyle.AppCode.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBD_COLOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CBD_COLOR()
        {
            this.GOOD_COLOR = new HashSet<GOOD_COLOR>();
        }
    
        public int COLORCODE { get; set; }
        public Nullable<int> COLLECTIONCODE { get; set; }
        public Nullable<int> IMAGECODE { get; set; }
        public string NAME { get; set; }
    
        public virtual CBD_COLLECTION CBD_COLLECTION { get; set; }
        public virtual IMAGE IMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOOD_COLOR> GOOD_COLOR { get; set; }
    }
}
