//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standartstyle.AppCode.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBD_MANUFACTURER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CBD_MANUFACTURER()
        {
            this.CBD_COLLECTION = new HashSet<CBD_COLLECTION>();
        }
    
        public int MANCODE { get; set; }
        public string NAME { get; set; }
        public string COUNTRY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CBD_COLLECTION> CBD_COLLECTION { get; set; }
    }
}
