//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standartstyle.AppCode.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOOD_ATTRIBUTES
    {
        public int GATCODE { get; set; }
        public Nullable<int> GOODCODE { get; set; }
        public Nullable<int> ATTRIBUTECODE { get; set; }
    
        public virtual ATTRIBUTES ATTRIBUTES { get; set; }
        public virtual GOODS GOODS { get; set; }
    }
}
