//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Standartstyle.AppCode.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOOD_COLOR
    {
        public int GCCODE { get; set; }
        public Nullable<int> COLORCODE { get; set; }
        public Nullable<int> GOODCODE { get; set; }
    
        public virtual CBD_COLOR CBD_COLOR { get; set; }
        public virtual GOODS GOODS { get; set; }
    }
}
